language: node_js
env:
  matrix:
  - secure: RnjP9KgKQqmCU/WzWlpTjGgDtIKQ3aYFx1QX8VptLhBoVqmuF7jOpoRn8fgZYlZFrgIjvPZO09GpDEaOCNoEeyrnPfTYpus3uXhb7youBIyFVPPXKKzMeco6Hky4EUvosDScKYKWg05yuI3p6aFMcFycIPNYezuFI4aEvs4wyi0KXuzw3ceEjpM5XJODYrjDgz7xZzQ58nRO9844w1QtocqlUnE93gNtzbDNrY83RqlUxKNUtirA8PmncfgvE8gRYfauNIPI2Q9x1RExe5HWeI2IatO72KTi5vFD0OTd1ZLRmXimAgg1Qja1y2g0S8PPx+07xArRkJaj+SFgWy2JalcVkzMnYWiiEMJvKSov39EGmiJ9bRRx2lmGMk+xjHHCP2Q8s58FdXtjrPBNRzzNHUdQpyY2EhQNLtGuKtDDFlDHkk8EviPAbeDcNB9kAUU9ZFN7wBst2Yaf5t9m/FFaMntinnPqz6Z0xD5qLjudCtmOHHGewQ9/XUJ2kwyct+AsKJXQ3Bu4KGS0sXm5NLtLoTIaw0DKKw2hvcREC4MdLddwFOBiKJKlGL2S4fOrU+RpyGVj7r60nhYCd0HVk4xC6m9rid/ceYN4zDEiRbGZHJghAnrxGZ/cX8HO2dx7qVeEsBsHcRsOqrPLsESLsOQNei0vZow1DMZOCPLyF8cpqPQ=
  - secure: B6ditpJWMeAZ39v64giMVzhxdDTrY/ltg5vBn/tB4SuG7OBqDMbIsCKR1njv2OgDNYXM2TcadYgXzoW6VPHZhz+AWr+rh+eXYAnO9Gf4Qtb4PBTLfL5ZnnOu2uG0gC+jAfAvp+wBPplR93fJUBVChJNeu+mSQSwv0b8Z33cSe4yLea6H7wA8mELGAebCYukHoCJoRlDweZGl4Y/8SQ6I4iW3wKP9cDkD33K/w5Zb0sIuXcpRxy+BZOfcgYV+q4Sa1S8urW9HlNUiH0jfG1xBzjxm6tbZ9q1p5AkgrhFBeO4afxtujcXT3ngrXsC1GkfO+Anr0FaMh1sRujY8Qo4Wy5DqUnDkQIj5cioleoZWyF+VJazCtDqlK4/TtB7ouH90lJaicf60upY0EB44cwB0VOMPtT3r/nOT+lNubAvFiX92UCrjUa3+6aHvrbWHHf+4OT8dYTr9BMCeptaPI46h5dlDM7Iu6vXfwBp+dNOZHeJ71hV0hjslpwCKQmZYjQBTSSVUdtVT3kuVqhYKTeTlqJoMhAchqJrEGWEUb8+xllEtg7mU2UVuS9s0p7lGtlgLExXcdcRR4FOT65+FiQ4J0nr3xLcPc/XvaZQwq5wr0veZZQGCVtFm7YzgCr9nqWsgYA5G5WOOMViskB/6ZRXx2TXsJE37ZeZE2Lpagvwo8xs=
services:
  - docker
branches:
  only:
    - master

before_install:
  - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t pea3nut/pea3nut-info:latest .
  - docker pubsh pea3nut/pea3nut-info:latest
